name: AOD API Automation

on:
  push:
    branches: [ "j-allure" ]
  pull_request:
    branches: [ "j-allure" ]
  schedule:
    - cron: '*/10 * * * 0-5'

jobs:
  AoD-API-Automation-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: |
          brew install allure
        working-directory: .
      - name: Create a temp artifact folder named `output`
        run: |
          mkdir output
      - name: Run tests with Maven
        run: mvn clean test
      - name: Collect Allure files and generate allure-report folder
        run: |
          pwd
          allure generate ./allure-results
      - name: Publishing Allure artifact to GitHub Actions
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report